import mongoose from "mongoose";

const AdsSchema = mongoose.Schema({
  adsonoff: { type: String },
  popup: { type: String },
  interstitial_count: { type: String },
  interstitial_tag: { type: String },
  appOpen_tag: { type: String },
  rewarded_tag: { type: String },
  native_top_tag: { type: String },
  native_bottom_tag: { type: String },
  banner_type_tag: { type: String },
  top_type: { type: String },
  bottom_type: { type: String },
  native_btn_type: { type: String },
  start_ads: { type: String },
  Version_Code: { type: String },
  update_link: { type: String },
  start_time: { type: String },
  back_btn_interstitial: { type: String },
  second_btn_opan_ads: { type: String },
  native_top_show: { type: String },
  native_bottom_show: { type: String },
  interstitial_preload: { type: String },
  native_preload: { type: String },
  admob_banner: { type: String },
  admob_interstitial: { type: String },
  admob_open: { type: String },
  admob_native_first: { type: String },
  admob_native_second: { type: String },
  admob_rewarded: { type: String },
  facebok_banner: { type: String },
  facebok_native_first: { type: String },
  facebok_native_second: { type: String },
  facebok_interstitial: { type: String },
  facebok_open: { type: String },
  facebok_rewarded: { type: String },
  btn_1_background: { type: String },
  btn_1_text: { type: String },
  btn_color_start: { type: String },
  btn_color_end: { type: String },
  btn_color_border_start: { type: String },
  btn_color_border_end: { type: String },
  btn_color_gradiant_angle: { type: String },
  btn_color_gradiant_border_angle: { type: String },
  btn_color_text: { type: String },
  btn_border_height: { type: String },
  btn_height: { type: String },
  btn_radius: { type: String },
  qureka_link: { type: String },
  interstitial_ad_cost:{type: String},
  native_ad_cost:{type: String}
  
},{ strict: false });

mongoose.models = {};
export default mongoose.model("Ads", AdsSchema);
